CREATE TABLE IF NOT EXISTS EMAILGENERATOR (
   ID INT,
   FIRST_NAME VARCHAR,
   LAST_NAME VARCHAR,
   EMAIL VARCHAR
);

DELETE FROM EMAILGENERATOR;

INSERT INTO EMAILGENERATOR (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (1, 'kk', 'ioio', 'kk-ioio@csii.co.jp');
INSERT INTO EMAILGENERATOR (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES (2, 'John', 'Doe', 'john.doe@example.com');
